name: consistency-policy
channels:
  - pytorch3d
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - absl-py
  - accelerate
  - aiohttp
  - aiosignal
  - alsa-lib
  - antlr-python-runtime
  - aom
  - arrow-cpp
  - asciitree
  - asttokens
  - async-timeout
  - attr
  - attrs
  - av
  - aws-c-cal
  - aws-c-common
  - aws-c-event-stream
  - aws-c-io
  - aws-checksums
  - aws-sdk-cpp
  - backports
  - backports.functools_lru_cache
  - blas
  - blas-devel
  - blinker
  - blosc
  - boto3
  - botocore
  - brotli
  - brotli-bin
  - brotli-python
  - brunsli
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cachetools
  - cairo
  - certifi
  - cffi
  - cfitsio
  - charls
  - charset-normalizer
  - click
  - cloudpickle
  - cmake
  - colorama
  - contourpy
  - cryptography
  - cudatoolkit
  - cycler
  - cython
  - cytoolz
  - dask-core
  - dataclasses
  - dav1d
  - dbus
  - debugpy
  - decorator
  - diffusers
  - dill
  - docker-pycreds
  - einops
  - entrypoints
  - exceptiongroup
  - executing
  - expat
  - ffmpeg
  - fftw
  - filelock
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freeglut
  - freetype
  - frozenlist
  - fsspec
  - fvcore
  - geos
  - gettext
  - gflags
  - giflib
  - gitdb
  - gitpython
  - glib
  - glib-tools
  - glog
  - gmp
  - gnutls
  - google-auth
  - google-auth-oauthlib
  - graphite2
  - grpc-cpp
  - grpcio
  - gst-plugins-base
  - gstreamer
  - gstreamer-orc
  - gym
  - h5py
  - harfbuzz
  - hdf5
  - hydra-core
  - icu
  - idna
  - imageio
  - imageio-ffmpeg
  - importlib-metadata
  - importlib_resources
  - iopath
  - ipykernel
  - ipython
  - jack
  - jasper
  - jedi
  - jmespath
  - jpeg
  - jupyter_client
  - jupyter_core
  - jxrlib
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - lerc
  - libabseil
  - libaec
  - libavif
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang
  - libcrc32c
  - libcups
  - libcurl
  - libdb
  - libdeflate
  - libdrm
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libflac
  - libgcrypt
  - libgfortran
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libglu
  - libgoogle-cloud
  - libgpg-error
  - libhwloc
  - libiconv
  - libidn2
  - liblapack
  - liblapacke
  - libllvm11
  - libllvm15
  - libnghttp2
  - libnsl
  - libogg
  - libopencv
  - libopus
  - libpciaccess
  - libpng
  - libpq
  - libprotobuf
  - libsndfile
  - libsodium
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libsystemd0
  - libtasn1
  - libthrift
  - libtiff
  - libtool
  - libudev1
  - libunistring
  - libutf8proc
  - libuuid
  - libuv
  - libva
  - libvorbis
  - libvpx
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzlib
  - libzopfli
  - llvm-openmp
  - locket
  - lz4-c
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mkl
  - mkl-devel
  - mkl-include
  - mpg123
  - msgpack-python
  - multidict
  - munkres
  - mysql-common
  - mysql-libs
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - nspr
  - nss
  - numcodecs
  - numpy
  - oauthlib
  - omegaconf
  - openh264
  - openjpeg
  - openssl
  - orc
  - p11-kit
  - packaging
  - pandas
  - parquet-cpp
  - parso
  - partd
  - pathtools
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - ply
  - portalocker
  - promise
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pulseaudio
  - pure_eval
  - py-opencv
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pygments
  - pyjwt
  - pymunk
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - python-xxhash
  - python_abi
  - pytorch
  - pytorch-mutex
  - pytorch3d
  - pytz
  - pyu2f
  - pywavelets
  - pyyaml
  - pyzmq
  - qt-main
  - re2
  - readline
  - regex
  - requests
  - requests-oauthlib
  - responses
  - rhash
  - rsa
  - s2n
  - s3transfer
  - scikit-image
  - scikit-video
  - scipy
  - sentry-sdk
  - setproctitle
  - setuptools
  - shapely
  - shortuuid
  - sip
  - six
  - smmap
  - stack_data
  - svt-av1
  - tabulate
  - tbb
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tensorboardx
  - termcolor
  - threadpoolctl
  - tifffile
  - tk
  - toml
  - tomli
  - toolz
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - wandb
  - wcwidth
  - werkzeug
  - wheel
  - x264
  - x265
  - xcb-util
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xkeyboard-config
  - xxhash
  - xz
  - yacs
  - yaml
  - yarl
  - zarr
  - zeromq
  - zfp
  - zipp
  - zlib
  - zlib-ng
  - zstd
  - pip:
      - aiohttp-cors==0.7.0
      - annotated-types==0.6.0
      - beautifulsoup4==4.12.2
      - blessed==1.20.0
      - colorful==0.5.5
      - datasets==2.16.0
      - distlib==0.3.7
      - dm-control==1.0.9
      - dm-env==1.6
      - dm-tree==0.1.8
      - egl-probe==1.0.2
      - etils==1.5.2
      - fasteners==0.15
      - free-mujoco-py==2.1.6
      - gdown==4.7.1
      - glfw==1.12.0
      - google-api-core==2.14.0
      - googleapis-common-protos==1.61.0
      - gpustat==1.1.1
      - huggingface-hub==0.20.1
      - imagecodecs==2022.9.26
      - joblib==1.3.2
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.7.1
      - labmaze==1.0.6
      - llvmlite==0.36.0
      - lxml==4.9.3
      - monotonic==1.6
      - mujoco==3.0.0
      - multiprocess==0.70.13
      - numba==0.53.1
      - nvidia-ml-py==12.535.133
      - opencensus==0.11.3
      - opencensus-context==0.1.3
      - parameterized==0.9.0
      - platformdirs==3.11.0
      - prometheus-client==0.13.1
      - protobuf==3.19.6
      - py-spy==0.3.14
      - pyarrow-hotfix==0.6
      - pybullet-svl==3.1.6.4
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pygame==2.1.2
      - pyopengl==3.1.7
      - pytorchvideo==0.1.5
      - r3m==0.0.0
      - ray==2.2.0
      - referencing==0.30.2
      - robomimic==0.2.0
      - robosuite==1.2.0
      - rpds-py==0.12.0
      - scikit-learn==1.3.2
      - smart-open==6.4.0
      - soupsieve==2.5
      - virtualenv==20.24.6
